fastAPI:
  SAVE_FRAMES_COUNT: 12
  VIDEOS_DIR_PATH: /app/test_videos # в контейнере
  FRAMES_DIR_PATH: /app/test_frames
  SQLALCHEMY_DATABASE_URI: postgresql://user:password@database:5432/dbname?sslmode=disable
  SQLALCHEMY_TEST_DATABASE_URI: postgresql://username:qwerty123@test_database:5432/test?sslmode=disable
