version: "3.9"

services:
  app:
    build: .
    command: bash -c "sleep 3s && python3 restore_init_db.py && uvicorn app:app"
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
